{
 "title": "ACP Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "metrics_job",
    "label": "Metrics Service",
    "query": {
     "query": "label_values(up{job=~\"aca|mts|acp\"}, job)"
    }
   },
   {
    "name": "app_name",
    "label": "Service Name",
    "query": "ACP Config Assistant,Metadata Transformation Service,Automated Curation Platform"
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"$metrics_job\", handler!=\"none\", handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"$metrics_job\", handler!=\"none\", handler!=\"/metrics\"}",
     "legendFormat": "{{method}} {{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"$metrics_job\", handler!=\"none\", handler!=\"/metrics\"} / http_request_duration_seconds_count{job=\"$metrics_job\", handler!=\"none\", handler!=\"/metrics\"}",
     "legendFormat": "{{method}} {{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"$metrics_job\", status=\"5xx\", handler!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"$metrics_job\", status=\"2xx\", handler!=\"none\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"$metrics_job\", handler!=\"none\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"$metrics_job\", status=\"4xx\", handler!=\"none\", handler!=\"/metrics\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_request_duration_seconds_bucket{job=\"$metrics_job\", handler!=\"none\", handler!=\"/metrics\"}[1m])) by(handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(http_requests_total{job=\"$metrics_job\", handler!=\"none\", handler!=\"/metrics\"}[30s]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$metrics_job\", handler!=\"/metrics\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Log Type Rate of \"$app_name\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate({job=\"$app_name\"}[1m]))",
     "legendFormat": "lines/s"
    }
   ]
  },
  {
   "title": "Log of Service: \"$app_name\"",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"$app_name\"}"
    }
   ]
  }
 ]
}